# Generated by Django 3.2.9 on 2023-06-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка для локации'),
        ),
        migrations.AlterField(
            model_name='placeoffice',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка для локации'),
        ),
    ]
