# Generated by Django 3.2.9 on 2023-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address_en',
            field=models.CharField(default=1, max_length=64, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.CharField(default=1, max_length=64, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='mail',
            field=models.EmailField(default=1, max_length=64, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default=1, max_length=16, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
