# Generated by Django 3.2.9 on 2023-06-07 12:26

import apps_en.main_page_en.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EllipseEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=16, null=True, verbose_name='Компаний')),
                ('countries', models.CharField(blank=True, max_length=16, null=True, verbose_name='Стран')),
                ('meetings', models.CharField(blank=True, max_length=16, null=True, verbose_name='B2B встречи')),
                ('exhibitors', models.CharField(blank=True, max_length=16, null=True, verbose_name='Экспонентов')),
            ],
            options={
                'verbose_name': 'Эллипс',
                'verbose_name_plural': 'Эллипс',
                'db_table': 'ellipse_en',
            },
        ),
        migrations.CreateModel(
            name='ForumEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок форма')),
                ('description', models.TextField(verbose_name='Описание форма')),
            ],
            options={
                'verbose_name': 'О форуме',
                'verbose_name_plural': 'О форуме',
                'db_table': 'forum_en',
            },
        ),
        migrations.CreateModel(
            name='MembersEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'db_table': 'members_en',
            },
        ),
        migrations.CreateModel(
            name='OrganizersEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название организации')),
                ('loga', models.ImageField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path, validators=[apps_en.main_page_en.services.validate_file_extension], verbose_name='Фотография нашего организаторa *(157x127)')),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
                'db_table': 'organizers_en',
            },
        ),
        migrations.CreateModel(
            name='PageOneEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path, verbose_name='Фотография')),
                ('year', models.CharField(blank=True, max_length=8, null=True, verbose_name='Год')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок Экспо')),
                ('description', models.TextField(verbose_name='Описание Экспо')),
            ],
            options={
                'verbose_name': 'Начало',
                'verbose_name_plural': 'Начало',
                'db_table': 'page_one_en',
            },
        ),
        migrations.CreateModel(
            name='PartnersEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название партнёра')),
                ('loga', models.ImageField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path, validators=[apps_en.main_page_en.services.validate_file_extension], verbose_name='Логотип нашего партнёра *(157x127)')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партёры',
                'db_table': 'partners_en',
            },
        ),
        migrations.CreateModel(
            name='PlaceEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('location', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка для локации')),
            ],
            options={
                'verbose_name': 'Локации',
                'verbose_name_plural': 'Локации',
                'db_table': 'location_en',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfficeEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('mail', models.URLField(blank=True, null=True, verbose_name='Почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('location', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка для локации')),
            ],
            options={
                'verbose_name': 'Локация офиса',
                'verbose_name_plural': 'Локация офиса',
                'db_table': 'location_office_en',
            },
        ),
        migrations.CreateModel(
            name='SectorsEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path, verbose_name='Фотография')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path, validators=[apps_en.main_page_en.services.validate_file_extension], verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок сектора')),
                ('description', models.TextField(verbose_name='Описание сектора')),
            ],
            options={
                'verbose_name': 'Секторы',
                'verbose_name_plural': 'Секторы',
                'db_table': 'sectors_en',
            },
        ),
        migrations.CreateModel(
            name='SocialsEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('snapchat', models.URLField(blank=True, null=True, verbose_name='Snapchat')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='Tiktok')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('wechat', models.URLField(blank=True, null=True, verbose_name='Wechat')),
            ],
            options={
                'verbose_name': 'Социальный сеть',
                'verbose_name_plural': 'Социальные сети',
                'db_table': 'socials_en',
            },
        ),
        migrations.CreateModel(
            name='SpeakersEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path, verbose_name='Фотография')),
                ('name', models.CharField(max_length=32, verbose_name='Полное имя')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
                'db_table': 'speakers_en',
            },
        ),
        migrations.CreateModel(
            name='SponsorsEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название спонсара')),
                ('loga', models.ImageField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path, validators=[apps_en.main_page_en.services.validate_file_extension], verbose_name='Фотография нашего спонсара *(157x127)')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
                'db_table': 'sponsors_en',
            },
        ),
        migrations.CreateModel(
            name='TargetEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Заголовок цели')),
                ('description', models.TextField(verbose_name='Описание цели')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'db_table': 'target_en',
            },
        ),
        migrations.CreateModel(
            name='TasksEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='Номер задач')),
                ('description', models.TextField(verbose_name='Описание задач')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks_en',
            },
        ),
        migrations.CreateModel(
            name='VideoEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок')),
                ('urel_video', models.URLField(max_length=128, verbose_name='Укажите ссылку на видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'db_table': 'video_en',
            },
        ),
        migrations.CreateModel(
            name='ZoneEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('image', models.ImageField(upload_to='apps/main_page/images/', verbose_name='Фотография')),
                ('title_one', models.CharField(blank=True, max_length=64, null=True, verbose_name='Дни')),
                ('title_two', models.CharField(blank=True, max_length=64, null=True, verbose_name='Основа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'zone_en',
            },
        ),
        migrations.CreateModel(
            name='CategoryEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path)),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps_en.main_page_en.services.get_upload_path, validators=[apps_en.main_page_en.services.validate_file_extension])),
                ('is_main', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main_page_en.categoryen')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category_en',
                'managed': True,
            },
        ),
    ]
